---
server:
  port: 8888
spring:
  security:
    user:
      name: uname
      password: pwd
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dhrub123/toll_service
          #username:
          #password: 
          search-paths:
          - 'station*'
          repos:
            performance:
              pattern: '*/perf'
              uri: https://github.com/dhrub123/toll_service_perf
              search-paths:
              - 'station*'