spring:
  mvc:
    favicon:
      enabled: false
  servlet:
    multipart:
      location: ${java.io.tmpdir}
      max-file-size: 50MB
      max-request-size: 50MB
 
#logging:
#  level:
#    org: debug

com:
  justgifit:
    optimize: true
    gif-location: ${java.io.tmpdir}/gif
   
      